/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IpoRouteImport } from './routes/ipo'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BondsRouteImport } from './routes/bonds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyTickerRouteImport } from './routes/company.$ticker'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoRoute = IpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsRoute = BondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTickerRoute = CompanyTickerRouteImport.update({
  id: '/company/$ticker',
  path: '/company/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/companies': typeof CompaniesRoute
  '/funds': typeof FundsRoute
  '/indices': typeof IndicesRoute
  '/ipo': typeof IpoRoute
  '/learn': typeof LearnRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/companies': typeof CompaniesRoute
  '/funds': typeof FundsRoute
  '/indices': typeof IndicesRoute
  '/ipo': typeof IpoRoute
  '/learn': typeof LearnRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/companies': typeof CompaniesRoute
  '/funds': typeof FundsRoute
  '/indices': typeof IndicesRoute
  '/ipo': typeof IpoRoute
  '/learn': typeof LearnRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/company/$ticker': typeof CompanyTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonds'
    | '/companies'
    | '/funds'
    | '/indices'
    | '/ipo'
    | '/learn'
    | '/members'
    | '/news'
    | '/company/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonds'
    | '/companies'
    | '/funds'
    | '/indices'
    | '/ipo'
    | '/learn'
    | '/members'
    | '/news'
    | '/company/$ticker'
  id:
    | '__root__'
    | '/'
    | '/bonds'
    | '/companies'
    | '/funds'
    | '/indices'
    | '/ipo'
    | '/learn'
    | '/members'
    | '/news'
    | '/company/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BondsRoute: typeof BondsRoute
  CompaniesRoute: typeof CompaniesRoute
  FundsRoute: typeof FundsRoute
  IndicesRoute: typeof IndicesRoute
  IpoRoute: typeof IpoRoute
  LearnRoute: typeof LearnRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  CompanyTickerRoute: typeof CompanyTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds': {
      id: '/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof BondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$ticker': {
      id: '/company/$ticker'
      path: '/company/$ticker'
      fullPath: '/company/$ticker'
      preLoaderRoute: typeof CompanyTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BondsRoute: BondsRoute,
  CompaniesRoute: CompaniesRoute,
  FundsRoute: FundsRoute,
  IndicesRoute: IndicesRoute,
  IpoRoute: IpoRoute,
  LearnRoute: LearnRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  CompanyTickerRoute: CompanyTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
